linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: unused-parameter
        severity: warning
      - name: blank-imports
        severity: warning
      - name: empty-block
        severity: warning
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["all", "-SA1019"]
  unused:
    check-exported: true

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - misspell
    - errcheck
    - gocyclo
    - ineffassign
    - typecheck
    - unused
    - gofmt
    - goimports
    - unconvert
    - unparam
  disable:
    - golint
    - scopelint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  sort-results: true